export { default as Header } from "./Header/Header"
export { default as GameDefault } from "./Game/GameDefault"
export { default as ModalOpen } from "./Modal/ModalOpen"
export { default as Modal } from "./Modal/Modal"
export { default as GamePlay } from "./Game/GamePlay"
