export { default as Header } from "./Header/Header"
export { default as GameDefault } from "./Game/GameDefault"
export { default as ModalOpen } from "./Modal/ModalOpen"
export { default as Modal } from "./Modal/Modal"
export { default as GameResults } from "./Game/GameResults"
export { default as Game } from "./Game/Game"
